services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  FreedomSex\ServerBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity}'


  FreedomSex\ServerBundle\EventListener\EntityDateUpdate:
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  # JsonEncode options
  app.json_encoder:
    class: Symfony\Component\Serializer\Encoder\JsonEncode
    arguments:
      - [ json_encode_options: JSON_UNESCAPED_UNICODE ]

  serializer.encoder.json:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder
    arguments:
      - '@app.json_encoder'

  app.cache.chain:
    class: Symfony\Component\Cache\Adapter\ChainAdapter
    arguments:
      $adapters: ['@app.cache.memory', '@app.cache.items']

  FreedomSex\Contracts\Entity\User:
    autoconfigure: true
