services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

#  A4Sex\ServerBundle\:
#    resource: '../src/*'
#    exclude: '../src/DependencyInjection'

  A4Sex\Services\EntityDateUpdater:
    arguments:
      $isLegacyFieldNames: true

  A4Sex\EventListener\EntityDateUpdate:
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  # JsonEncode options
  app.json_encoder:
    class: Symfony\Component\Serializer\Encoder\JsonEncode
    arguments:
      - { "json_encode_options": !php/const JSON_UNESCAPED_UNICODE }

  serializer.encoder.json:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder
    arguments:
      - '@app.json_encoder'

  app.cache.chain:
    class: Symfony\Component\Cache\Adapter\ChainAdapter
    arguments:
      $adapters: ['@app.cache.memory', '@app.cache.items']

#  A4Sex\Contracts\Entity\User:
#    autoconfigure: true

  A4Sex\AttachedStorage: ~
  A4Sex\KeyValueStorage: ~
  A4Sex\ClientIdentifier: ~
